#+TITLE: SpectraGAN

This repo contains a dataset of synthetic mobile traffic for 5 cities in Germany generated using publicly available context data for those cities as input to the pre-trained SpectraGAN model.
We also include the input context data as part of the dataset.

* Context data
We provide the context data for 5 cities in Germany: Aachen, Bonn, Dresden, Frankfurt and Munich.
The context data is a set of layers of publicly available information of a city as 2D images, one for each of the 27 contextual attributes.
This includes census data (i.e. population), 12 types of land uses (e.g. where or not a location is green area) and 14 types of points of interest (e.g. whether or not a location is a cafe).
See Section 3.1, Figure 5 and Table 1 in the paper for the full list with description of the context data as well as how it is collected.

* Synthetic mobile traffic data
We provide synthetic spatio-temporal mobile traffic data that is generated by inputting the provided context data into the pre-trained SpectraGAN model.
The spatial size of the data for each city varies depending on the spatial size of context data for that city.
Specifically, the size of the traffic data is smaller than that of the context data as the margin context is not enough for conditional generation.
For the time dimension, the total length of the data is 3 weeks with hourly granularity, i.e. 24x7x3 = 504 time steps.

* The data generation process
The provided synthetic data is generated in two steps to comply with the NDAs that cover the operator provided original mobile traffic datasets and support for this work.
We train the SpectraGAN model using one-month long original mobile traffic data for 9 cities in Country 1 (City A to City I as described in Section 3.1) and their associated publicly available context data.
We use this trained SpectraGAN model to generate the mobile traffic data for the above-mentioned 5 cities in Germany by giving their respective context data as input to the model.
